version: '3.1'

services:
  db:
    image: postgres:13.1
    privileged: true
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: aleksandrandreev
      POSTGRES_PASSWORD: w3qxst1ck
      POSTGRES_DB: library
  backend:
    build:
      context: .
    expose:
      - 8080
    command: bash -c "
      ./wait-for-postgres.sh db
      && python manage.py migrate
      && gunicorn service.wsgi -b 0.0.0.0:8080
      "
    depends_on:
      - db
  nginx:
    build: ./nginx
    ports:
      - 8000:80
    depends_on:
      - backend
  frontend:
    build: ./service/frontend
    ports:
      - 80:80
    depends_on:
      - nginx